(library
 (name granary_sql)
 (public_name granary.sql)
 (libraries
  lwt
  granary.encoding
  granary.store
  granary.catalog
  granary.columnar
  uutf
  uucp)
 (preprocess
  (pps lwt_ppx))
 (instrumentation
  (backend bisect_ppx)))

(menhir
 (modules parser)
 (flags --unused-tokens))

(ocamllex lexer)
