(library
 (name sqlocaml_sql)
 (public_name sqlocaml.sql)
 (libraries
  lwt
  sqlocaml.encoding
  sqlocaml.store
  sqlocaml.catalog
  sqlocaml.columnar
  uutf
  uucp)
 (preprocess
  (pps lwt_ppx))
 (instrumentation
  (backend bisect_ppx)))

(menhir
 (modules parser)
 (flags --unused-tokens))

(ocamllex lexer)
