(library
 (name jepsen_lib)
 (wrapped false)
 (modules
  edn_history
  workload_list_append
  workload_bank
  workload_set
  workload_counter
  nemesis)
 (libraries granary granary.unix lwt lwt.unix unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name harness)
 (modules harness)
 (libraries
  jepsen_lib
  granary
  granary.unix
  granary.store
  mirage-crypto-rng
  mirage-crypto-rng.unix
  lwt
  lwt.unix
  unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name negative_control)
 (modules negative_control)
 (libraries jepsen_lib unix))
