#!/usr/bin/env bash
# Generate test coverage report using bisect_ppx.
#
# Usage:
#   ./scripts/coverage.sh             # summary to stdout
#   ./scripts/coverage.sh html        # summary + HTML in _coverage/
#   ./scripts/coverage.sh ci          # fail if below COVERAGE_THRESHOLD (default 85%)
#
# Requires: granary-dev Podman image (built from Containerfile, includes bisect_ppx).
# Run from the repo root.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
THRESHOLD="${COVERAGE_THRESHOLD:-85}"
MODE="${1:-summary}"

PODMAN="podman run --rm -v ${REPO}:/workspace:Z -w /workspace granary-dev"

echo "==> Building and running instrumented test suite..."
$PODMAN bash -c "
  dune clean 2>/dev/null || true
  dune runtest --instrument-with bisect_ppx 2>/dev/null
" 2>&1

COVFILES=$($PODMAN bash -c "find _build -name '*.coverage' | tr '\n' ' '" 2>/dev/null)

if [ -z "${COVFILES// }" ]; then
  echo "ERROR: no coverage files generated. Is bisect_ppx installed in granary-dev?" >&2
  exit 1
fi

# parser.ml and lexer.ml are generated by Menhir / ocamllex — not handwritten.
# bisect-ppx-report has no --exclude flag, so we filter the per-file output ourselves.
GENERATED="lib/sql/parser.ml lib/sql/lexer.ml"

handwritten_summary() {
  # Run per-file report inside container, filter generated files, recompute total.
  $PODMAN bash -c "
    COVFILES=\$(find _build -name '*.coverage' 2>/dev/null | tr '\n' ' ')
    bisect-ppx-report summary --per-file \$COVFILES 2>&1
  " | python3 -c "
import sys, re

generated = {'lib/sql/parser.ml', 'lib/sql/lexer.ml'}
total_hit = 0
total_pts = 0
lines = []

for line in sys.stdin:
    line = line.rstrip()
    m = re.match(r'\s*(\d+\.\d+)\s*%\s+(\d+)/(\d+)\s+(.+)', line)
    if m:
        pct, hit, pts, path = m.group(1), int(m.group(2)), int(m.group(3)), m.group(4).strip()
        if path not in generated:
            total_hit += hit
            total_pts += pts
            lines.append(line)
    # else: skip summary line (will recompute)

for l in lines:
    print(l)

overall = 100.0 * total_hit / total_pts if total_pts else 0.0
print(f'{overall:6.2f} %  {total_hit:4d}/{total_pts:4d}   Handwritten total (excl. generated parser+lexer)')
"
}

case "$MODE" in
  html)
    mkdir -p "$REPO/_coverage"
    chmod 777 "$REPO/_coverage"
    $PODMAN bash -c "
      COVFILES=\$(find _build -name '*.coverage' 2>/dev/null | tr '\n' ' ')
      bisect-ppx-report html -o _coverage \$COVFILES
    " 2>&1
    sudo chown -R "$(id -un):$(id -gn)" "$REPO/_coverage" 2>/dev/null || true
    handwritten_summary
    echo ""
    echo "==> Full HTML report: _coverage/index.html"
    ;;
  ci)
    SUMMARY=$(handwritten_summary)
    echo "$SUMMARY"
    PCT=$(echo "$SUMMARY" | tail -1 | python3 -c "import sys,re; m=re.search(r'(\d+\.\d+)\s*%', sys.stdin.read()); print(m.group(1)) if m else print(0)")
    echo ""
    echo "==> Handwritten coverage: ${PCT}%  (threshold: ${THRESHOLD}%)"
    if python3 -c "import sys; exit(0 if float('${PCT}') >= float('${THRESHOLD}') else 1)"; then
      echo "PASS"
    else
      echo "FAIL: ${PCT}% < threshold ${THRESHOLD}%" >&2
      exit 1
    fi
    ;;
  summary|*)
    handwritten_summary
    ;;
esac
